/**
 * Docs Generator Tests
 */

import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { createDependencyGraph } from '../../src/core/dependency-graph.js';
import { createDocsGenerator } from '../../src/core/docs-generator.js';

describe('Docs Generator', () => {
  const tmpDir = join(process.cwd(), '.test-docs-tmp');

  beforeEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
    mkdirSync(join(tmpDir, 'src', 'core'), { recursive: true });
    mkdirSync(join(tmpDir, 'src', 'utils'), { recursive: true });
  });

  afterEach(() => {
    rmSync(tmpDir, { recursive: true, force: true });
  });

  function writeFile(relativePath: string, content: string) {
    writeFileSync(join(tmpDir, relativePath), content, 'utf-8');
  }

  describe('generate', () => {
    it('should generate markdown content', async () => {
      writeFile(
        'package.json',
        JSON.stringify({
          name: 'test-project',
          version: '1.0.0',
          scripts: { test: 'vitest run', build: 'tsc' },
        }),
      );
      writeFile('src/index.ts', 'export const x = 1;');

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('test-project');
      expect(content).toContain('Auto-generated by Cortex');
    });

    it('should include commands from package.json', async () => {
      writeFile(
        'package.json',
        JSON.stringify({
          name: 'test',
          version: '1.0.0',
          scripts: {
            test: 'vitest run',
            build: 'tsc',
            lint: 'biome check',
          },
        }),
      );

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('## Commands');
      expect(content).toContain('npm run test');
      expect(content).toContain('npm run build');
      expect(content).toContain('npm run lint');
    });

    it('should detect tech stack from dependencies', async () => {
      writeFile(
        'package.json',
        JSON.stringify({
          name: 'test',
          version: '1.0.0',
          dependencies: { zod: '^3.0.0' },
          devDependencies: {
            typescript: '^5.0.0',
            vitest: '^1.0.0',
            '@biomejs/biome': '^1.0.0',
          },
        }),
      );

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('TypeScript');
      expect(content).toContain('Vitest');
      expect(content).toContain('Biome');
      expect(content).toContain('Zod');
    });

    it('should include entry points', async () => {
      writeFile('src/index.ts', 'export const x = 1;');
      writeFile('package.json', JSON.stringify({ name: 'test', version: '1.0.0' }));

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('Entry Points');
      expect(content).toContain('src/index.ts');
    });

    it('should include module structure', async () => {
      writeFile('src/core/auth.ts', 'export function auth() {}');
      writeFile('src/core/user.ts', 'export function user() {}');
      writeFile('src/utils/hash.ts', 'export function hash() {}');
      writeFile('package.json', JSON.stringify({ name: 'test', version: '1.0.0' }));

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('Structure');
    });

    it('should include dependency graph when provided', async () => {
      writeFile('src/utils/helper.ts', 'export function helper() {}');
      writeFile(
        'src/core/a.ts',
        "import { helper } from '../utils/helper.js';\nexport function a() { helper(); }",
      );
      writeFile(
        'src/core/b.ts',
        "import { helper } from '../utils/helper.js';\nexport function b() { helper(); }",
      );
      writeFile('package.json', JSON.stringify({ name: 'test', version: '1.0.0' }));

      const graph = createDependencyGraph({ projectRoot: tmpDir });
      await graph.build();

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: true,
      });

      const content = await generator.generate(graph);

      expect(content).toContain('Hot Dependencies');
    });

    it('should include cortex optimization section when .cortex exists', async () => {
      mkdirSync(join(tmpDir, '.cortex'), { recursive: true });
      writeFile('.cortex/config.yaml', 'pruning:\n  threshold: 5');
      writeFile('package.json', JSON.stringify({ name: 'test', version: '1.0.0' }));

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('Cortex Optimization');
    });

    it('should include custom sections', async () => {
      writeFile('package.json', JSON.stringify({ name: 'test', version: '1.0.0' }));

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
        customSections: ['## Custom Section\nCustom content here'],
      });

      const content = await generator.generate();

      expect(content).toContain('## Custom Section');
      expect(content).toContain('Custom content here');
    });
  });

  describe('edge cases', () => {
    it('should handle missing package.json', async () => {
      writeFile('src/index.ts', 'export const x = 1;');

      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();

      expect(content).toContain('Project');
      expect(content.length).toBeGreaterThan(0);
    });

    it('should handle empty project', async () => {
      const generator = createDocsGenerator({
        projectRoot: tmpDir,
        includeGraph: false,
      });

      const content = await generator.generate();
      expect(content.length).toBeGreaterThan(0);
    });
  });
});
